<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2009-10-17 16:25

$extensionPath = t3lib_extMgm::extPath('imagemap_wizard');
return array(
	'tx_imagemapwizard_parser' => $extensionPath . 'classes/class.tx_imagemapwizard_parser.php',
	'tx_imagemapwizard_softrefproc' => $extensionPath . 'classes/class.tx_imagemapwizard_softrefproc.php',
	'tx_imagemapwizard_wizicon' => $extensionPath . 'classes/class.tx_imagemapwizard_wizicon.php',
	'tx_imagemapwizard_controller_wizard' => $extensionPath . 'classes/controller/class.tx_imagemapwizard_controller_wizard.php',
	'tx_imagemapwizard_model_dataobject' => $extensionPath . 'classes/model/class.tx_imagemapwizard_model_dataObject.php',
	'tx_imagemapwizard_model_mapper' => $extensionPath . 'classes/model/class.tx_imagemapwizard_model_mapper.php',
	'tx_imagemapwizard_model_typo3env' => $extensionPath . 'classes/model/class.tx_imagemapwizard_model_typo3env.php',
	'tx_imagemapwizard_view_abstract' => $extensionPath . 'classes/view/class.tx_imagemapwizard_view_abstract.php',
	'tx_imagemapwizard_view_tceform' => $extensionPath . 'classes/view/class.tx_imagemapwizard_view_tceform.php',
	'tx_imagemapwizard_view_wizard' => $extensionPath . 'classes/view/class.tx_imagemapwizard_view_wizard.php',
);
?>